// <auto-generated />
using System;
using JobbPilot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobbPilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513074336_AddAuditLogPayload")]
    partial class AddAuditLogPayload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobbPilot.Domain.Applications.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverLetter")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("cover_letter");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("GhostedThresholdDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(21)
                        .HasColumnName("ghosted_threshold_days");

                    b.Property<Guid?>("JobAdId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_ad_id");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_seeker_id");

                    b.Property<DateTimeOffset>("LastStatusChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_status_change_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("JobbPilot.Domain.Applications.ApplicationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.HasKey("Id")
                        .HasName("pk_application_notes");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_application_notes_application_id");

                    b.ToTable("application_notes", (string)null);
                });

            modelBuilder.Entity("JobbPilot.Domain.Applications.FollowUp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset?>("OutcomeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("outcome_at");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.HasKey("Id")
                        .HasName("pk_follow_ups");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_follow_ups_application_id");

                    b.ToTable("follow_ups", (string)null);
                });

            modelBuilder.Entity("JobbPilot.Domain.Auditing.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_type");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("ImpersonatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("impersonated_by");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id", "OccurredAt")
                        .HasName("pk_audit_log");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("JobbPilot.Domain.Invitations.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_admin_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origin");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid?>("RedeemedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("redeemed_by_user_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_admin_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token_hash");

                    b.HasIndex("Status", "Email")
                        .HasDatabaseName("ix_invitations_status_email");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("JobbPilot.Domain.JobAds.JobAd", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_job_ads");

                    b.ToTable("job_ads", (string)null);
                });

            modelBuilder.Entity("JobbPilot.Domain.JobSeekers.JobSeeker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_job_seekers");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_seekers_user_id");

                    b.ToTable("job_seekers", (string)null);
                });

            modelBuilder.Entity("JobbPilot.Domain.Resumes.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_seeker_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_resumes");

                    b.HasIndex("JobSeekerId")
                        .HasDatabaseName("ix_resumes_job_seeker_id");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("JobbPilot.Domain.Resumes.ResumeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_resume_versions");

                    b.HasIndex("ResumeId")
                        .HasDatabaseName("ix_resume_versions_resume_id");

                    b.ToTable("resume_versions", (string)null);
                });

            modelBuilder.Entity("JobbPilot.Domain.Waitlist.WaitlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_admin_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid?>("RejectedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("rejected_by_admin_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid?>("ResultingInvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("resulting_invitation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_waitlist_entries");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_waitlist_entries_email")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("Status", "RequestedAt")
                        .HasDatabaseName("ix_waitlist_entries_status_requested_at");

                    b.ToTable("waitlist_entries", (string)null);
                });

            modelBuilder.Entity("JobbPilot.Domain.Applications.ApplicationNote", b =>
                {
                    b.HasOne("JobbPilot.Domain.Applications.Application", null)
                        .WithMany("Notes")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_notes_applications_application_id");
                });

            modelBuilder.Entity("JobbPilot.Domain.Applications.FollowUp", b =>
                {
                    b.HasOne("JobbPilot.Domain.Applications.Application", null)
                        .WithMany("FollowUps")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follow_ups_applications_application_id");
                });

            modelBuilder.Entity("JobbPilot.Domain.JobAds.JobAd", b =>
                {
                    b.OwnsOne("JobbPilot.Domain.JobAds.Company", "Company", b1 =>
                        {
                            b1.Property<Guid>("JobAdId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("company_name");

                            b1.HasKey("JobAdId");

                            b1.ToTable("job_ads");

                            b1.WithOwner()
                                .HasForeignKey("JobAdId")
                                .HasConstraintName("fk_job_ads_job_ads_id");
                        });

                    b.OwnsOne("JobbPilot.Domain.JobAds.ExternalReference", "External", b1 =>
                        {
                            b1.Property<Guid>("JobAdId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("external_id");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("external_source");

                            b1.HasKey("JobAdId");

                            b1.HasIndex("Source", "ExternalId")
                                .IsUnique()
                                .HasDatabaseName("ix_job_ads_external_source_external_id")
                                .HasFilter("\"external_id\" IS NOT NULL");

                            b1.ToTable("job_ads");

                            b1.WithOwner()
                                .HasForeignKey("JobAdId")
                                .HasConstraintName("fk_job_ads_job_ads_id");
                        });

                    b.Navigation("Company")
                        .IsRequired();

                    b.Navigation("External");
                });

            modelBuilder.Entity("JobbPilot.Domain.JobSeekers.JobSeeker", b =>
                {
                    b.OwnsOne("JobbPilot.Domain.JobSeekers.Preferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("JobSeekerId");

                            b1.Property<bool>("EmailNotifications");

                            b1.Property<string>("Language")
                                .IsRequired();

                            b1.Property<bool>("WeeklySummary");

                            b1.HasKey("JobSeekerId");

                            b1.ToTable("job_seekers");

                            b1
                                .ToJson("preferences")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("JobSeekerId")
                                .HasConstraintName("fk_job_seekers_job_seekers_id");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("JobbPilot.Domain.Resumes.ResumeVersion", b =>
                {
                    b.HasOne("JobbPilot.Domain.Resumes.Resume", null)
                        .WithMany("Versions")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_versions_resumes_resume_id");
                });

            modelBuilder.Entity("JobbPilot.Domain.Applications.Application", b =>
                {
                    b.Navigation("FollowUps");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("JobbPilot.Domain.Resumes.Resume", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
