// JobAd skill-taxonomy snapshot generator — F4-4 (job-ad keyword/skill extraction).
//
// Off-build, manually run generator (ADR 0043 Beslut B — hermetic build: NO
// build-time fetch, NO runtime external hop). The JSON file
// `src/Jobbliggaren.Infrastructure/Taxonomy/jobad-skill-taxonomy.v30.json` is the
// source of truth in the repo; this script is its auditable reproduction.
//
// Fetches the deterministic skill vocabulary the extractor matches ad terms
// against, from the JobTech Taxonomy v1 GraphQL (taxonomy.api.jobtechdev.se,
// EPL-2.0). Two layers (OQ4 "JobTech-taxonomi-synonymer (ESCO) först"):
//   - `skill`      — AF "kompetens" concepts (Swedish skill buckets); the
//                    alternative_labels/hidden_labels are the synonym layer.
//   - `esco-skill` — the ESCO skill layer integrated into the JobTech taxonomy
//                    (Swedish preferred labels; alternative_labels are EMPTY in
//                    the JobTech GraphQL — itself an OQ4 finding).
// Each entry: { conceptId, preferredLabel, layer, synonyms[] } where synonyms =
// dedup(alternative_labels ++ hidden_labels). Deterministically sorted on
// (layer, conceptId) for diff-stability. Version-pinned to v30 to align with
// taxonomy-snapshot.json.
//
// Run: node tools/jobad-skill-taxonomy/generate.mjs
// Requires: Node 18+ (built-in fetch). No npm dependency.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { byConceptId } from '../taxonomy-snapshot/lib.mjs';

const GRAPHQL = 'https://taxonomy.api.jobtechdev.se/v1/taxonomy/graphql';
const TAXONOMY_VERSION = '30';
const FETCHED_AT = '2026-06-15';

const here = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(
  here,
  '../../src/Jobbliggaren.Infrastructure/Taxonomy/jobad-skill-taxonomy.v30.json',
);

async function gql(query) {
  const res = await fetch(`${GRAPHQL}?query=${encodeURIComponent(query)}`);
  const body = await res.json();
  if (!res.ok || body.errors) {
    throw new Error(`GraphQL ${res.status}: ${JSON.stringify(body.errors ?? body).slice(0, 300)}`);
  }
  if (!Array.isArray(body.data?.concepts)) {
    throw new Error(`Unexpected GraphQL response: ${JSON.stringify(body).slice(0, 300)}`);
  }
  return body.data.concepts;
}

// Dedup + trim synonym surface forms; drop blanks and any equal to the
// preferred label (case-insensitive) so the asset carries only ADDITIONAL forms.
function cleanSynonyms(preferred, alternative, hidden) {
  const seen = new Set([preferred.trim().toLowerCase()]);
  const out = [];
  for (const raw of [...(alternative ?? []), ...(hidden ?? [])]) {
    const s = (raw ?? '').trim();
    if (!s) continue;
    const key = s.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(s);
  }
  return out;
}

async function fetchLayer(type) {
  const raw = await gql(
    `{ concepts(type:"${type}") { id preferred_label alternative_labels hidden_labels } }`,
  );
  const entries = [];
  for (const c of raw) {
    const preferred = (c.preferred_label ?? '').trim();
    if (!c.id || !preferred) continue; // deprecated/blank — skip (fail-quiet at item level)
    entries.push({
      conceptId: c.id,
      preferredLabel: preferred,
      layer: type,
      synonyms: cleanSynonyms(preferred, c.alternative_labels, c.hidden_labels),
    });
  }
  return entries;
}

async function main() {
  console.log('Fetching AF skill concepts (type: skill)...');
  const skills = await fetchLayer('skill');
  console.log(`  ${skills.length} skill concepts (${skills.filter((s) => s.synonyms.length).length} with synonyms)`);

  console.log('Fetching ESCO skill concepts (type: esco-skill)...');
  const escoSkills = await fetchLayer('esco-skill');
  console.log(`  ${escoSkills.length} esco-skill concepts (${escoSkills.filter((s) => s.synonyms.length).length} with synonyms)`);

  const all = [...skills, ...escoSkills].sort(
    (a, b) => (a.layer < b.layer ? -1 : a.layer > b.layer ? 1 : byConceptId(a, b)),
  );

  const totalSynonyms = all.reduce((n, s) => n + s.synonyms.length, 0);

  const snapshot = {
    source: 'JobTech Taxonomy API (taxonomy.api.jobtechdev.se) v1 GraphQL',
    license: 'EPL-2.0 (JobTech Taxonomy) — see THIRD-PARTY-NOTICES.md',
    taxonomyVersion: TAXONOMY_VERSION,
    fetchedAt: FETCHED_AT,
    note:
      'F4-4 skill vocabulary for deterministic job-ad keyword/skill extraction (ADR 0071/0074, OQ4). ' +
      'Generated by tools/jobad-skill-taxonomy/generate.mjs. Two layers: AF "skill" (kompetens) + ' +
      'ESCO "esco-skill". synonyms = dedup(alternative_labels ++ hidden_labels) minus the preferred label. ' +
      'The extractor (JobAdKeywordExtractor) builds a lexeme-set -> conceptId index over preferredLabel + ' +
      'synonyms via ITextAnalyzer.ToLexemes(Swedish). Frozen, version-pinned v30 (aligns taxonomy-snapshot.json).',
    counts: {
      skill: skills.length,
      escoSkill: escoSkills.length,
      total: all.length,
      synonymStrings: totalSynonyms,
    },
    skills: all,
  };

  writeFileSync(OUT_PATH, JSON.stringify(snapshot, null, 2) + '\n', 'utf8');
  console.log(`Wrote ${OUT_PATH}`);
  console.log(`  v${TAXONOMY_VERSION}: ${all.length} skill concepts, ${totalSynonyms} synonym strings.`);
}

main().catch((err) => {
  console.error('ERROR:', err.message);
  process.exit(1);
});
